"""Script to read the selected wpath from json file generated by the interpolation module"""

import argparse
import json

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file", help="File to open")
    parser.add_argument(
        "-p", "--param", help="Parameter to read, one of ['qc', 'wpath']"
    )

    args = parser.parse_args()

    with open(args.file, "r") as f:
        a = json.load(f)

        print(a[args.param])

    exit(0)
